name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. سحب كود المشروع من GitHub
    - uses: actions/checkout@v4

    # 2. إعداد بيئة JDK 11
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # 3. بناء المشروع باستخدام Gradle المثبت في البيئة مباشرة (بدون استخدام gradlew)
    - name: Build with Gradle
      run: gradle build
